import type { NextConfig } from "next";
import { withSentryConfig } from "@sentry/nextjs";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "*.supabase.co",
        pathname: "/storage/v1/object/public/**",
      },
    ],
  },
  experimental: {
    serverActions: {
      bodySizeLimit: "5mb",
    },
  },
};

// withSentryConfig adds the Sentry webpack plugin for source-map
// upload, wires the tunnel route to dodge ad-blockers, and injects
// the SDK into server/edge/client bundles. Build-time env vars
// (SENTRY_ORG, SENTRY_PROJECT, SENTRY_AUTH_TOKEN) are read from
// process.env; when they're absent the wrapper still works but skips
// source-map upload.
export default withSentryConfig(nextConfig, {
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  authToken: process.env.SENTRY_AUTH_TOKEN,

  // Proxy Sentry's ingest endpoint through our own origin so ad
  // blockers and corporate firewalls don't drop client error reports.
  // Route handler is auto-generated by Sentry at this path.
  tunnelRoute: "/monitoring",

  // Don't spam local dev logs; only show build output in CI.
  silent: !process.env.CI,

  // Automatically upload source maps in CI and delete them from the
  // client bundle afterwards so they aren't served publicly.
  sourcemaps: {
    deleteSourcemapsAfterUpload: true,
  },
});
