import type { NextConfig } from "next";
import { withSentryConfig } from "@sentry/nextjs";

const securityHeaders = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-XSS-Protection", value: "1; mode=block" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
  { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
];

const nextConfig: NextConfig = {
  async headers() {
    return [{ source: "/(.*)", headers: securityHeaders }];
  },
  async redirects() {
    return [
      // /privacy is its own page; /terms?tab=privacy is handled in proxy.ts so
      // the destination doesn't carry the now-meaningless `tab` query.
      // Refund still lives under /terms tabs.
      { source: "/refund-policy", destination: "/terms?tab=refund", permanent: true },
      // Legacy PM routes → creator equivalents (permanent 308)
      { source: "/apply/pm", destination: "/apply/creator", permanent: true },
      { source: "/api/pm-apply", destination: "/api/creator-apply", permanent: true },
      { source: "/api/admin/pm/:id", destination: "/api/admin/creator/:id", permanent: true },
      { source: "/admin/project-managers", destination: "/dashboard/admin/creators", permanent: true },
      { source: "/dashboard/admin/pms", destination: "/dashboard/admin/creators", permanent: true },
      // Legacy browser-print export → new react-pdf checklist. Keep this
      // permanent redirect so bookmarks, pasted links, and any old
      // marketing copy still resolve to the actual download.
      { source: "/for-creators/launch-guide/print", destination: "/api/launch-guide/pdf", permanent: true },
      // Common-sense aliases for the signup route — the canonical path is
      // /register but external write-ups, marketing emails, and our own
      // preview gate have linked to /sign-up. Next preserves the
      // ?redirectTo=... query string through redirect, so post-signup
      // bounce-back to /projects/create still works.
      { source: "/sign-up", destination: "/register", permanent: true },
      { source: "/signup", destination: "/register", permanent: true },
      // Old /admin/* tree consolidated into /dashboard/admin/*. Keep these
      // redirects so any existing bookmarks or external links still resolve.
      { source: "/admin", destination: "/dashboard", permanent: true },
      { source: "/admin/categories", destination: "/dashboard/admin/categories", permanent: true },
      { source: "/admin/creators", destination: "/dashboard/admin/creators", permanent: true },
      { source: "/admin/kyc", destination: "/dashboard/admin/kyc", permanent: true },
      { source: "/admin/projects", destination: "/dashboard/admin/projects", permanent: true },
      { source: "/admin/queue", destination: "/dashboard/admin/queue", permanent: true },
      { source: "/admin/users", destination: "/dashboard/admin/users", permanent: true },
    ];
  },
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "*.supabase.co",
        pathname: "/storage/v1/object/public/**",
      },
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
      },
      {
        protocol: "https",
        hostname: "*.googleusercontent.com",
      },
    ],
  },
  experimental: {
    serverActions: {
      bodySizeLimit: "5mb",
    },
  },
};

// withSentryConfig adds the Sentry webpack plugin for source-map
// upload, wires the tunnel route to dodge ad-blockers, and injects
// the SDK into server/edge/client bundles. Build-time env vars
// (SENTRY_ORG, SENTRY_PROJECT, SENTRY_AUTH_TOKEN) are read from
// process.env; when they're absent the wrapper still works but skips
// source-map upload.
export default withSentryConfig(nextConfig, {
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  authToken: process.env.SENTRY_AUTH_TOKEN,

  // Proxy Sentry's ingest endpoint through our own origin so ad
  // blockers and corporate firewalls don't drop client error reports.
  // Route handler is auto-generated by Sentry at this path.
  tunnelRoute: "/monitoring",

  // Don't spam local dev logs; only show build output in CI.
  silent: !process.env.CI,

  // Required for Turbopack (Next.js 16 default). Source maps upload
  // via Next's `runAfterProductionCompile` hook instead of the webpack
  // plugin. Sentry's docs claim this is the Turbopack default, but in
  // practice (@sentry/nextjs 10.49) the hook doesn't fire unless you
  // set this explicitly.
  useRunAfterProductionCompileHook: true,

  // Automatically upload source maps in CI and delete them from the
  // client bundle afterwards so they aren't served publicly.
  sourcemaps: {
    deleteSourcemapsAfterUpload: true,
  },
});
